#jdbc.driver=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://localhost:3306/itcast?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#jdbc.username=root
#jdbc.password=202815
#
#username=kang6666



#TODO 配置数据源相关信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itcast? #ServierTimezone=TUC
    username: root
    password: 202815
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    banner-mode: off


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url:jdbc:mysql://localhost:3306/itcast?
#    uesername: root
#    password: 202815
#    type: com.alibaba.druid.pool.DruidDataSource
#  main:
#    banner-mode: off